import { message, user, test } from "./library.js";
import { messageOne, userOne, testOne } from "./library.js";
import { messageTwo, userTwo as us, testTwo } from "./library.js";
import * as yahoo from "./library.js";
import { default as yahooOne } from "./libraryOne.js";
import yahooTwo from "./libraryTwo.js";
import { messageFour, userFour } from "./libraryTwo.js";
import { userFive } from "./bridge.js";
console.log("message: ", message);
console.log("messageOne: ", messageOne);
console.log("messageTwo: ", messageTwo);
console.log("messageThree: ", yahoo.messageThree);
console.log("messageFour: ", messageFour);
console.log(user("Yahoo Baba"));
console.log(userOne("Yahoo Baba"));
console.log(us("Yahoo Baba"));
console.log(yahoo.userThree("Yahoo Baba"));
console.log(userFour("Yahoo Baba"));
document.body.innerHTML = message;
let a = new test();
let b = new testOne();
let c = new testTwo();
let d = new yahoo.testThree();
yahooOne();
yahooTwo();
